### POST - 예약 생성
POST {{root-path}}/api/reservations
Content-Type: application/json
Authorization: Bearer {{authorizationToken}}

{
  "mentor": 2,
  "mentee": 1,
  "reservationStatus": "PAID",
  "reservationStartAt": "2025-06-15 22:55:00",
  "reservationEndAt": "2025-06-15 23:08:00"
}